### ISSUE TITLE
Standalone RServer instance has no dedicated app window

### ISSUE THREAD

**Issue by pat-s** [hrbrmstr/RSwitch#7]
By this I mean that the window created by RSwitch for the RStudio Server instance does not appear as a instance in the dock. 
This means one cannot "CMD + Tab" back to the instance or select it from the dock.

I have no clue how complicated this would be - but would it be possible to add this?
Preferably as its own "Rswitch" instance but a second browser instance would also be fine.

Right now the only way to find the instance again is to look in the mission control overview and select it - which stopped me from using it since this takes too long :/

Thanks for all the work on this! 🚀

**Comment by hrbrmstr** [comment]
Thx for using RSwitch & taking the time to file an issue!

If you [re-]enable showing RSwitch itself in the Dock, you can cmd-tab to it and then Cmd-~ to each RStudio Server instance window.

If that doesn't do the trick, def make a note here and I can def make a slight tweak for what you're looking for since I was thinking of having it as an option. That is, if I include a small helper app with the the main app, I can support Cmd-Tab (since the helper app wld open separate app instances for RStudio Server processes) as well as launching RStudio Server connections from things like Terminal.app

**Comment by pat-s** [comment]
Thanks! I probably removed the app icon myself at some point.

Works great for me now. Even reconnecting after a VPN disconnect works flawlessly and on the first try much smoother than in the browser.
Switching between windows makes the experience even better. Great!
